// src/pages/NotFoundPage.jsx

import React from "react";

export default function NotFoundPage() {
  return (
    <div className="bg-[#ECEFF1] text-[rgba(0,0,0,0.87)] font-sans min-h-screen flex items-center justify-center px-4">
      <div className="bg-white max-w-[360px] w-full p-6 pb-4 rounded shadow-md">
        <h2 className="text-[#888] font-normal text-sm my-4">404</h2>
        <h1 className="text-[22px] font-light text-[rgba(0,0,0,0.6)] mb-4">
          Page Not Found
        </h1>
        <p className="text-sm leading-[1.4] mb-6">
          The specified file was not found on this website. Please check the URL
          for mistakes and try again.
        </p>
        <h3 className="text-[#ffa100] font-bold text-sm mb-2">
          Why am I seeing this?
        </h3>
        <p className="text-sm leading-[1.4] mb-6">
          This page was generated by the Firebase Command-Line Interface. To
          modify it, edit the <code>404.html</code> file in your project's
          configured <code>public</code> directory.
        </p>
        <a
          href="/"
          className="block text-center bg-[#039be5] uppercase no-underline text-white py-4 rounded shadow-md"
        >
          Go Home
        </a>
      </div>
    </div>
  );
}